//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableDesignInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableDesignInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   
        ///IF NOT EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;COMMENT&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, N&apos;COLUMN&apos;,N&apos;{1}&apos;))
        ///EXEC sys.sp_addextendedproperty @name=N&apos;COMMENT&apos;, @value=N&apos;{2}&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;, @level2type=N&apos;COLUMN&apos;,@level2name=N&apos;{1}&apos;
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddColumnComment {
            get {
                return ResourceManager.GetString("AddColumnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///IF NOT EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;MS_Description&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, N&apos;COLUMN&apos;,N&apos;{1}&apos;))
        ///EXEC sys.sp_addextendedproperty @name=N&apos;MS_Description&apos;, @value=N&apos;{2}&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;, @level2type=N&apos;COLUMN&apos;,@level2name=N&apos;{1}&apos;
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddColumnDescription {
            get {
                return ResourceManager.GetString("AddColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///IF NOT EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;COMMENT&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;,NULL,NULL))
        ///EXEC sys.sp_addextendedproperty @name=N&apos;COMMENT&apos;, @value=N&apos;{1}&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddTableComment {
            get {
                return ResourceManager.GetString("AddTableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF NOT EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;MS_Description&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;,NULL,NULL))
        ///EXEC sys.sp_addextendedproperty @name=N&apos;MS_Description&apos;, @value=N&apos;{1}&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddTableDescription {
            get {
                return ResourceManager.GetString("AddTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------------------------CREATE TABLE:{0}【{1}】---------------------------------------------------
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{0}]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[{0}](
        ///{2}{3}
        ///) ON [PRIMARY]
        ///END
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF  EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;COMMENT&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, N&apos;COLUMN&apos;,N&apos;{1}&apos;))
        ///EXEC sys.sp_dropextendedproperty @name=N&apos;COMMENT&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;, @level2type=N&apos;COLUMN&apos;,@level2name=N&apos;{1}&apos;
        ///GO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropColumnComment {
            get {
                return ResourceManager.GetString("DropColumnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF  EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;MS_Description&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, N&apos;COLUMN&apos;,N&apos;{1}&apos;))
        ///EXEC sys.sp_dropextendedproperty @name=N&apos;MS_Description&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;, @level2type=N&apos;COLUMN&apos;,@level2name=N&apos;{1}&apos;
        ///GO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropColumnDescription {
            get {
                return ResourceManager.GetString("DropColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[{0}]&apos;) AND type in (N&apos;U&apos;))
        ///DROP TABLE [dbo].[{0}]
        ///GO
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTable {
            get {
                return ResourceManager.GetString("DropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF  EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;MS_Description&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, NULL,NULL))
        ///EXEC sys.sp_dropextendedproperty @name=N&apos;MS_Description&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;
        ///IF  EXISTS (SELECT * FROM ::fn_listextendedproperty(N&apos;COMMENT&apos; , N&apos;SCHEMA&apos;,N&apos;dbo&apos;, N&apos;TABLE&apos;,N&apos;{0}&apos;, NULL,NULL))
        ///EXEC sys.sp_dropextendedproperty @name=N&apos;COMMENT&apos; , @level0type=N&apos;SCHEMA&apos;,@level0name=N&apos;dbo&apos;, @level1type=N&apos;TABLE&apos;,@level1name=N&apos;{0}&apos;
        ///
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDescription {
            get {
                return ResourceManager.GetString("DropTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /****** Object:  Table [dbo].[TableLayoutInfo]    Script Date: 2015/12/17 21:45:30 ******/
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[TableLayoutInfo]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[TableLayoutInfo](
        ///	[TableName] [nvarchar](200) NOT NULL,
        ///	[TableDisplayName] [nvarchar](200) NULL,
        ///	[ColumnName] [nvarchar](200) NOT NULL,
        ///	[ColumnDisplayName] [nvarchar](200) NULL,
        ///	[DataType] [nvarchar](100) NULL,
        ///	[Length] [int] NULL,
        ///	[Precision] [int] NULL,
        ///	[Sc [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateTableinfo {
            get {
                return ResourceManager.GetString("UpdateTableinfo", resourceCulture);
            }
        }
    }
}
